# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main", "Features/*" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Check bicep version
        run: az bicep version

      - name: Build azuredeploy.bicep --> azuredeploy.json
        run: az bicep build --file "azuredeploy.bicep" --outfile "azuredeploy.json"

      - name: Commit changes
        if: always()
        run: |
          git config --global user.email "github-actions@noreply.github.com"
          git config --global user.name "Github-Action Build"

          git add azuredeploy.json

          if ! git diff-index --quiet HEAD --; then
            git commit -m "Github action: Build"
            git push
          fi

