name: Build

on:
  push:
    branches: [ "main", "Features/*" ]
  pull_request:
    branches: [ "main" ]

  # Allows running this workflow manually from the Actions tab
  workflow_dispatch:

permissions: 
  contents: read

jobs:
  build:
    permissions:
      contents: write # for git push
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Check bicep version
        run: az bicep version

      - name: Build azuredeploy.bicep --> azuredeploy.json
        run: az bicep build --file "azuredeploy.bicep" --outfile "azuredeploy.json"

      - name: Commit changes
        if: always()
        run: |
          git config --global user.email "github-actions@noreply.github.com"
          git config --global user.name "Github-Action Build"

          git add azuredeploy.json

          if ! git diff-index --quiet HEAD --; then
            git commit -m "Github action: Build"
            git push
          fi

